-   id: clj-kondo
    name: clj-kondo
    description: '`clj-kondo` is a command-line utility for enforcing style consistency across Clojure projects.'
    entry: clj-kondo
    language: clojure
    types: [clojure]
    require_serial: true
