FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y curl \
    && mkdir -p /usr/local/bin

ARG TARGETARCH
ARG TARGETOS

COPY ${TARGETOS}/${TARGETARCH}/clj-kondo /usr/local/bin/clj-kondo

RUN chmod +x /usr/local/bin/clj-kondo

CMD ["clj-kondo"]
