FROM alpine:3

# amd64 or arm64
ARG TARGETARCH

COPY clj-kondo-${TARGETARCH} /bin/clj-kondo

RUN chmod +x /bin/clj-kondo

RUN apk --no-cache add curl ca-certificates tar && \
    curl -Ls https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk > /tmp/glibc-2.28-r0.apk && \
    apk add --allow-untrusted --force-overwrite /tmp/glibc-2.28-r0.apk
RUN echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

CMD ["clj-kondo"]
