#!/usr/bin/env bash

install_dir=${1:-/tmp/clojure}
mkdir -p "$install_dir"
cd /tmp
curl -O -sL https://download.clojure.org/install/clojure-tools-1.10.0.442.tar.gz
tar xzf clojure-tools-1.10.0.442.tar.gz
cd clojure-tools
lib_dir="$install_dir/lib"
mkdir -p "$lib_dir/libexec"
cp ./*.jar "$lib_dir/libexec"

mkdir -p "$install_dir/bin"
cp clojure "$install_dir/bin"
cp clj "$install_dir/bin"

cd /tmp
rm -rf clojure-tools-1.10.0.442.tar.gz
rm -rf clojure-tools
export PATH="$PATH:$install_dir/bin"
