#!/usr/bin/env bash

set -eo pipefail

curl --fail https://raw.githubusercontent.com/technomancy/leiningen/refs/tags/2.9.10/bin/lein > lein
sudo mkdir -p /usr/local/bin/
sudo mv lein /usr/local/bin/lein
sudo chmod a+x /usr/local/bin/lein
