#!/usr/bin/env bash

rm performance.txt
echo -e "==== Build initial cache" | tee -a performance.txt
cp="$(clojure -Spath)"
(time ./clj-kondo --lint "$cp" --cache) 2>&1 | tee -a performance.txt

echo -e "\n==== Lint a single file (emulate in-editor usage)" | tee -a performance.txt
(time ./clj-kondo --lint src/clj_kondo/main.clj --cache) 2>&1 | tee -a performance.txt

count=$(find . -name "*.clj*" -type f | wc -l | tr -d ' ')
echo -e "\n==== Launch clj-kondo for each file in project ($count)" | tee -a performance.txt
(time find src -name "*.clj*" -type f -exec ./clj-kondo --lint {} --cache \; ) 2>&1 | tee -a performance.txt
