#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp clj-kondo /tmp/release
cp performance.txt /tmp/release
VERSION=$(cat resources/CLJ_KONDO_VERSION)

cd /tmp/release

## release binary as zip archive

zip "clj-kondo-$VERSION-$CLJ_KONDO_PLATFORM-amd64.zip" clj-kondo

## cleanup

rm clj-kondo
