#!/usr/bin/env bash

rm -rf /tmp/built-in
mkdir -p /tmp/built-in
version=$(cat resources/CLJ_KONDO_VERSION)
echo "$version"

clojure -M:clj-kondo --lint "$(clojure -Spath -A:cljs)" --cache /tmp/built-in

base_path="/tmp/built-in/$version"

rm "$base_path"/clj/clojure.tools.reader.*.transit.json
rm "$base_path"/cljs/cljs.tools.reader.*transit.json

cp "$base_path"/clj/clojure.*.transit.json resources/clj_kondo/impl/cache/built_in/clj
cp "$base_path"/cljs/cljs.*.transit.json resources/clj_kondo/impl/cache/built_in/cljs
cp "$base_path"/cljs/clojure.*.transit.json resources/clj_kondo/impl/cache/built_in/cljs
cp "$base_path"/cljc/cljs.*.transit.json resources/clj_kondo/impl/cache/built_in/cljc

script/dump_types.clj
