#!/usr/bin/env bash

rm -rf /tmp/cljdoc
mkdir -p /tmp/cljdoc
version=$(cat resources/CLJ_KONDO_VERSION)

echo "---- cljdoc preview: installing jar in local repo"
lein install

echo "---- cljdoc preview: ingesting clj-kondo"
docker run --rm -v "$PWD:/clj-kondo" \
       -v "$HOME/.m2:/root/.m2" -v /tmp/cljdoc:/app/data --entrypoint "clojure" \
       cljdoc/cljdoc -A:cli ingest -p clj-kondo/clj-kondo -v "$version" \
       --git /clj-kondo

echo "---- cljdoc preview: starting server on port 8000"
docker run --rm -p 8000:8000 -v /tmp/cljdoc:/app/data cljdoc/cljdoc
