#!/usr/bin/env bash

# mkdir -p target/classes

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

clojure -Sdeps '{:deps {org.clojure/clojure {:mvn/version "1.10.0"}}}' -Spath

# javac java-src/clj_kondo/LockFix.java \
#       -cp ~/.m2/repository/org/clojure/clojure/1.10.0/clojure-1.10.0.jar \
#       -d target/classes

"$GRAALVM_HOME/bin/gu" install native-image

 # important, -J options go after --verbose
# CLJ_KONDO_GRAALVM=true clojure -J-Xmx250m -A:native-image

CLJ_KONDO_VERSION=$(cat resources/CLJ_KONDO_VERSION)

lein do clean, uberjar
$GRAALVM_HOME/bin/native-image \
  -jar target/clj-kondo-$CLJ_KONDO_VERSION-standalone.jar \
  -H:Name=clj-kondo \
  -H:+ReportExceptionStackTraces \
  -J-Dclojure.spec.skip-macros=true \
  -J-Dclojure.compiler.direct-linking=true \
  "-H:IncludeResources=clj_kondo/impl/cache/built_in/.*" \
  -H:ReflectionConfigurationFiles=reflection.json \
  --initialize-at-build-time  \
  -H:Log=registerResource: \
  --verbose \
  --no-fallback \
  --no-server \
  "-J-Xmx3g"
