#!/usr/bin/env bash

rm -rf classes
mkdir -p classes
mkdir -p /tmp/jdk

if [ ! -d "/tmp/jdk" ]; then
    git clone https://github.com/openjdk/jdk.git /tmp/jdk || true
else
    git -C /tmp/jdk pull
fi

# this script requires JAVA_HOME to be set to JDK 11 or later
if [ -z "$JAVA_HOME" ]; then
    export JAVA_HOME=~/Downloads/jdk-11.0.2.jdk/Contents/Home
fi

clojure -C:extract -e "(compile 'clj-kondo.impl.ExtractJava)"
clojure -A:extract -m clj-kondo.impl.ExtractJava
