#!/usr/bin/env bash

JAVA_VERSION=$(java -version 2>&1 | sed -n ';s/.* version "\(.*\)\.\(.*\)\..*"/\1\2/p;' | cut -f 1 -d " ")

if [ -z "$JAVA_HOME" ] || [ "$JAVA_VERSION" -lt 110 ]; then
    echo "Set JAVA_HOME to JDK 11 or later."
    exit 1
fi

rm -rf classes
mkdir -p classes
mkdir -p /tmp/jdk

if [ ! -d "/tmp/jdk" ]; then
    git clone https://github.com/openjdk/jdk.git /tmp/jdk || true
else
    git -C /tmp/jdk pull
fi

clojure -C:extract -e "(compile 'clj-kondo.impl.ExtractJava)"
clojure -A:extract -m clj-kondo.impl.ExtractJava "resources/clj_kondo/impl/cache/built_in/clj" \
        "-public" "--source-path" "/tmp/jdk/src/java.base/share/classes" \
        "java.lang" "java.math"
