#!/usr/bin/env bash

# requires JDK 11: JAVA_HOME=~/Downloads/jdk-11.0.2.jdk/Contents/Home
# also assumes a checkout of OpenJDK (https://github.com/openjdk/jdk.git) in /Users/Borkdude/git/jdk
rm -rf classes
mkdir -p classes
clojure -C:extract -e "(compile 'clj-kondo.impl.ExtractJava)"
clojure -A:extract -m clj-kondo.impl.ExtractJava
