#!/usr/bin/env bash

exit 0

set -eo pipefail

# shellcheck disable=1091
source script/extract-versions

if [ "$CLJ_KONDO_TEST_ENV" = "native" ]; then
    clojure -M:test
else
    echo "Testing with Clojure 1.9.0"
    clojure -Sforce -M:clojure-1.9.0:test
    lein with-profiles +clojure-1.9.0 "do" clean, test

    echo "Testing with Clojure 1.10.2"
    clojure -Sforce -M:clojure-1.10.2:test
    lein with-profiles +clojure-1.10.2 "do" clean, test
fi

echo "Pod test"
clojure -M:test:pod-test -d pod-test
