#!/usr/bin/env bash

# err=0
# function _trap_error() {
#     local exit_code="$1"
#     if [ "$exit_code" -eq 2 ]; then
#         err |= "$exit_code"
#     fi
# }

# trap '_trap_error $?' ERR
# trap 'exit $err' SIGINT SIGTERM

clojure -Sdeps '{:deps {org.clojure/clojure {:mvn/version "1.10.1"}}}' -Spath > /dev/null
clojure -Sdeps '{:deps {org.clojure/clojurescript {:mvn/version "1.10.520"}}}' -Spath > /dev/null
clojure -A:test

# sexit "$err"
