#!/usr/bin/env bash

set -eo pipefail

# populate mvn cache for extract tests
clojure -Sdeps '{:deps {org.clojure/clojure {:mvn/version "1.9.0"}}}' -Spath > /dev/null
clojure -Sdeps '{:deps {org.clojure/clojure {:mvn/version "1.10.2"}}}' -Spath > /dev/null
clojure -Sdeps '{:deps {org.clojure/clojurescript {:mvn/version "1.10.773"}}}' -Spath > /dev/null

if [ "$CLJ_KONDO_TEST_ENV" = "native" ]; then
    clojure -M:test
else
    echo "Testing with Clojure 1.9.0"
    clojure -Sforce -M:clojure-1.9.0:test
    lein with-profiles +clojure-1.9.0 "do" clean, test

    echo "Testing with Clojure 1.10.2"
    clojure -Sforce -M:clojure-1.10.2:test
    lein with-profiles +clojure-1.10.2 "do" clean, test
fi

clojure -A:test:pod-test -d pod-test
