#!/usr/bin/env clojure -Sdeps {:deps,{selmer,{:mvn/version,"1.12.17"}}}

(require '[selmer.parser :as p])
(require '[clojure.java.io :as io])
(require '[clojure.string :as str])
(require '[clojure.edn :as edn])

(def version (str/trim (slurp (io/file "resources/CLJ_KONDO_VERSION"))))

(def deps-edn (edn/read-string (slurp "deps.edn")))

(def deps-dependencies (:deps deps-edn))
(def lein-dependencies (cons '[org.clojure/clojure "1.9.0"]
                        (map (fn [[k v]]
                               [k (:mvn/version v)])
                             deps-dependencies)))

(spit "project.clj" (str ";; GENERATED by script/update-project.clj, DO NOT EDIT\n"
                         (p/render (slurp (io/file "project.clj.template"))
                                   {:version version
                                    :dependencies
                                    (format "[%s]"
                                            (str/join "\n                 "
                                                      lein-dependencies))})))
