#!/usr/bin/env clojure -Sdeps {:deps,{selmer,{:mvn/version,"1.12.17"}}}

(require '[selmer.parser :as p])
(require '[clojure.java.io :as io])
(require '[clojure.string :as str])

(def version (str/trim (slurp (io/file "resources/CLJ_KONDO_VERSION"))))

(spit "project.clj" (str ";; GENERATED by script/update-project.clj, DO NOT EDIT\n"
                         (p/render (slurp (io/file "project.clj.template")) {:version version})))
